# Generated by Django 6.0.4 on 2026-04-25 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('high', 'Yuqori'), ('medium', 'O‘rta'), ('low', 'Past')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('trend', models.CharField(max_length=100)),
                ('trend_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('institution_type', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('complaints', models.CharField(max_length=100)),
                ('checks_count', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('batch_number', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FaceIDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('verified', 'Tasdiqlandi'), ('suspicious', 'Shubhali'), ('failed', 'Rad etildi')], max_length=30)),
                ('checked_time', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_records', to='app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ExpirationMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('critical', 'Juda xavfli'), ('warning', 'Diqqat kerak'), ('safe', 'Xavfsiz')], max_length=20)),
                ('action_required', models.CharField(max_length=150)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiration_records', to='app.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Bajarildi'), ('current', 'Jarayonda'), ('pending', 'Kutilmoqda')], max_length=30)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='app.medicine')),
            ],
        ),
    ]
