# Generated by Django 6.0.4 on 2026-04-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceidrecord',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_id/'),
        ),
        migrations.AlterField(
            model_name='faceidrecord',
            name='status',
            field=models.CharField(choices=[('verified', 'Tasdiqlandi'), ('suspicious', 'Shubhali'), ('failed', 'Rad etildi')], default='verified', max_length=30),
        ),
    ]
