# Generated by Django 6.0.4 on 2026-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_confirm_and_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceidrecord',
            options={'verbose_name': 'Face ID profil', 'verbose_name_plural': 'Face ID profillar'},
        ),
        migrations.AlterField(
            model_name='faceidattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='checks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='complaints',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='rating',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(default='Faol', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicineclaim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
